import { Heading } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Auth from '../components/Auth';
import { useUser } from '../components/context/auth.context';

export default function Home() {
  const { session } = useUser();
  const router = useRouter();

  if (session) {
    router.push('/home');
  }
  return (
    <div>
      <Head>
        <title>Pro courses</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Auth />
    </div>
  );
}
