import { Heading } from '@chakra-ui/react';
import Head from 'next/head';
import Auth from '../components/Auth';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Auth />
    </div>
  );
}
