import { Box, Button, Heading } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useUser } from '../components/context/auth.context';
import Main from '../components/Home/Main';
import Navbar from '../components/Navbar';

export default function Home() {
  const { session } = useUser();
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Pro courses</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>

      <Box className='top-page'>
        <Navbar />
        <Main />
      </Box>
    </div>
  );
}
